[tool.poetry]
name = "opentype-feature-freezer"
version = "1.32.2"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.10"
fonttools = "^4.0"

[tool.poetry.scripts]
pyftfeatfreeze = "opentype_feature_freezer.cli:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
