[tool.poetry]
name = "chws-tool"
version = "1.4.1"
description = ""
authors = []
packages = [{include = "chws_tool"}]

[tool.poetry.dependencies]
python = "^3.10"
east-asian-spacing = ">=1.3.4"
setuptools = "^68.1.2"
setuptools-scm = "^7.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
